version: "2"
services:
    mysql:
        container_name: mysqldb
        build: ./sql
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=NBA_19_20
        ports:
            - "3306:3306"
            # - "33060:33060"

    # jtree:
    #    container_name: jtree
    #    build: ./
    #    ports:
    #        - "8000:8000"
    #    links:
    #        - mysql
    # limsinsight:
    #    container_name: limsinsight
    #    build: ./limsinsight
    #    ports:
    #        - "8003:8003"
    #    links:
    #        - mysql
    #        - jtree
    #    depends_on:
    #        - mysql
    #        - jtree
